main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:ad_id>/', views.detail_ad, name='detail_ad'),
    path('<int:ad_id>/send_response/', views.send_response, name='send_response'),
    path('create_ad/', views.create_ad, name='create_ad'),
]

service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/confirm_code/', views.confirm_code, name='confirm_code'),
    path('my_ads/', views.my_ads, name='my_ads'),
    path('my_ads/<int:ad_id>/', views.my_ad_detail, name='my_ad_detail'),
    path('my_ads/<int:ad_id>/edit_ad/', views.edit_ad, name='edit_ad'),
    path('my_responses/', views.my_responses, name='my_responses'),
    path('responses_on_my_ads/', views.responses_on_my_ads, name='responses_on_my_ads'),
    path('responses_on_my_ads/delete/<int:ad_id>/', views.delete_response, name='delete_response'),
    path('responses_on_my_ads/accept/<int:ad_id>/', views.accept_response, name='accept_response'),
    path('newsletter/', views.newsletter, name='newsletter'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Кастомизированная модель пользователя."""
    email = models.EmailField(unique=True)
    confirmation_code = models.CharField(max_length=6, blank=True, null=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from main.models import Ad
from users.models import User


class SignUpForm(UserCreationForm):
    """Форма регистрации пользователя."""
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    email = forms.EmailField(label='Адрес электронной почты', widget=forms.EmailInput(attrs={
        'class': 'form-control',
    }))
    password1 = forms.CharField(label='Пароль',
                                help_text='''<ul>
                                                <li>Пароль не должен быть слишком похож на другую вашу личную информацию.</li>
                                                <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                                <li>Пароль не должен быть слишком простым и распространенным.</li>
                                                <li>Пароль не может состоять только из цифр.</li>
                                            </ul>''',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                }))
    password2 = forms.CharField(label='Подтверждение пароля',
                                help_text='Для подтверждения введите, пожалуйста, пароль ещё раз.',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                }))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserAuthenticationForm(AuthenticationForm):
    """Форма входа."""
    username = forms.EmailField(label='Адрес электронной почты', widget=forms.EmailInput(attrs={
        'class': 'form-control',
    }))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))


class ConfirmationCodeForm(forms.Form):
    """Форма подтверждения кода."""
    confirmation_code = forms.CharField(label='Код подтверждения', max_length=6,
                                        help_text='На ваш электронный адрес был выслан код подтверждения',
                                        widget=forms.NumberInput(attrs={
                                            'class': 'form-control',
                                        }))


class ResponseFilterForm(forms.Form):
    """Форма фильтрации откликов."""
    ad = forms.ModelChoiceField(queryset=Ad.objects.none(), widget=forms.Select(attrs={
        'class': 'form-control'
    }), empty_label="All Ads", required=False)

    def __init__(self, user, *args, **kwargs):
        super(ResponseFilterForm, self).__init__(*args, **kwargs)
        self.fields['ad'].queryset = Ad.objects.filter(author=user)


class NewsletterForm(forms.Form):
    """Форма новостной рассылки."""
    header = forms.CharField(label='Заголовок', widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    text = forms.CharField(label='Текст', widget=forms.Textarea(attrs={
        'class': 'form-control'
    }))

users/views.py
import random

from django.conf import settings
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from main.forms import AdForm
from main.models import Ad, MediaFile, Response
from .forms import SignUpForm, UserAuthenticationForm, ConfirmationCodeForm, ResponseFilterForm, NewsletterForm
from .models import User


def register(request):
    """Функция-представление регистрации пользователя."""
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])

            confirmation_code = str(random.randint(100000, 999999))
            user.confirmation_code = confirmation_code
            user.save()

            send_mail(
                'Код подтверждения',
                f'Ваш код подтверждения: {confirmation_code}',
                settings.DEFAULT_FROM_EMAIL,
                [user.email],
                fail_silently=False,
            )

            return redirect('users:confirm_code')
    else:
        form = SignUpForm()
    return render(request, 'users/user/register.html', {'form': form})


def login_user(request):
    """Функция-представление входа пользователя."""
    if request.method == 'POST':
        form = UserAuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user, backend='users.authentication.EmailAuthBackend')
                return redirect('main:index')
    else:
        form = UserAuthenticationForm()
    return render(request, 'users/user/login.html', {'form': form})


def logout_user(request):
    """Функция-представление выхода пользователя."""
    logout(request)
    return redirect('main:index')


def confirm_code(request):
    """Функция-представление подтверждения."""
    if request.method == 'POST':
        form = ConfirmationCodeForm(request.POST)
        if form.is_valid():
            confirmation_code = form.cleaned_data['confirmation_code']
            user = User.objects.filter(confirmation_code=confirmation_code).first()

            if user:
                user.confirmation_code = None
                user.save()
                login(request, user, backend='users.authentication.EmailAuthBackend')
                return redirect('main:index')

    else:
        form = ConfirmationCodeForm()

    return render(request, 'users/user/confirm_code.html', {'form': form})


@login_required
def my_ads(request):
    """Функция-представление объявлений созданных текущим пользователем."""
    ads = Ad.objects.filter(author=request.user)
    context = {'ads': ads}
    return render(request, 'users/my_ads.html', context)


@login_required
def my_ad_detail(request, ad_id):
    """Функция-представление объявления созданного текущим пользователем."""
    ad = get_object_or_404(Ad, author=request.user, pk=ad_id)
    context = {'ad': ad}
    return render(request, 'users/my_ad_detail.html', context)


@login_required
def edit_ad(request, ad_id):
    """Функция-представление редактирования объявления, созданного текущим пользователем."""
    ad = get_object_or_404(Ad, author=request.user, pk=ad_id)
    if request.method == 'POST':
        form = AdForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            ad.header = cd['header']
            ad.category = cd['category']
            ad.body = cd['body']
            ad.save()
            if request.FILES.getlist('media_files'):
                for file in MediaFile.objects.filter(ad=ad):
                    file.delete()
                for file in request.FILES.getlist('media_files'):
                    MediaFile.objects.create(ad=ad, file=file)
            return redirect('users:my_ad_detail', ad_id=ad.id)
    else:
        form = AdForm(instance=ad)
    context = {'form': form, 'ad': ad}
    return render(request, 'users/edit_ad.html', context)


@login_required
def my_responses(request):
    """Функция-представление откликов, которые сделал текущий пользователь."""
    responses = Response.objects.filter(user=request.user)
    context = {'responses': responses}
    return render(request, 'users/my_responses.html', context)


@login_required
def responses_on_my_ads(request):
    """Функция-представление откликов на объявления созданные текущим пользователем."""
    current_user = request.user
    ads = Ad.objects.filter(author=current_user)
    user_responses = Response.objects.filter(ad__in=ads, ad__executor=None)
    form = ResponseFilterForm(user=current_user, data=request.GET)
    selected_ad = form['ad'].value()

    if selected_ad:
        user_responses = user_responses.filter(ad=selected_ad)
    context = {'responses': user_responses, 'form': form, 'selected_ad': selected_ad}
    return render(request, 'users/responses_on_my_ads.html', context)


@login_required
def delete_response(request, ad_id):
    """Функция-представление удаления объявления, созданного текущим пользователем."""
    ad = Ad.objects.get(pk=ad_id)
    ad.delete()
    return redirect('users:responses_on_my_ads')


@login_required
def accept_response(request, ad_id):
    """Функция-представление принятия отклика на созданное текущим пользователем объявление."""
    ad = Ad.objects.get(pk=ad_id)
    ad.executor = request.user
    ad.save()
    send_mail(
        'Ваш отклик был принят',
        f'Ваш отклик на объявлении "{ad.header}" был принят',
        settings.DEFAULT_FROM_EMAIL,
        [ad.executor.email],
        fail_silently=True,
    )
    return redirect('users:responses_on_my_ads')


def newsletter(request):
    """Функция-представление отправки новостной рассылки."""
    if request.user.is_staff:
        print(User.objects.all().values_list('email'))
        if request.method == 'POST':
            form = NewsletterForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                send_mail(
                    cd['header'],
                    cd['text'],
                    settings.DEFAULT_FROM_EMAIL,
                    User.objects.all().values_list('email', flat=True),
                    fail_silently=True,
                )
                return redirect('users:newsletter')
        else:
            form = NewsletterForm()
        context = {'form': form}
        return render(request, 'users/newsletter.html', context)
    raise Http404()

users/templates/users/edit_ad.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'users:my_ads' %}">Мои объявления</a></li>
            <li class="breadcrumb-item"><a
                    href="{% url 'users:my_ad_detail' ad.id %}">{{ ad.header|truncatechars:50 }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактирование</li>
        </ol>
    </nav>
    <h1>Редактирование "{{ ad.header }}"</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for f in form %}
            <div class="mb-3">
                <label class="form-label">{{ f.label }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
{% endblock %}

users/templates/users/my_ad_detail.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ ad.header|truncatechars:50 }}</li>
        </ol>
    </nav>
    <h1>{{ ad.header }}</h1>
    <hr>
    <h3>Категория: {{ ad.category }}</h3>
    <br>
    <a href="{% url 'users:edit_ad' ad.id %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-pencil-square"
             viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd"
                  d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
        </svg>
    </a>
    <br>
    <br>
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
            {% for media_file in ad.media_files.all %}
                <button type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide-to="{{ forloop.counter0 }}"
                        {% if forloop.counter0 == 0 %}class="active"{% endif %}
                        aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            {% for media_file in ad.media_files.all %}
                <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                    {% if media_file.return_file_name.lower == 'видео' %}
                        <video controls class="d-block w-100">
                            <source src="{{ media_file.file.url }}" type="video/mp4">
                            Ваш браузер не поддерживает тег video.
                        </video>
                    {% elif media_file.return_file_name.lower == 'изображение' %}
                        <img src="{{ media_file.file.url }}" class="d-block w-100" alt="...">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        {% if ad.media_files.count > 1 %}
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        {% endif %}
    </div>
    <br>
    <div style="font-size: 20px;">
        {{ ad.body }}
    </div>
    <br>
    <br>
{% endblock %}

users/templates/users/my_ads.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Мои объявления</li>
        </ol>
    </nav>
    <h1>Мои объявления</h1>
    <hr>
    <a href="{% url 'main:create_ad' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-plus-square"
             viewBox="0 0 16 16">
            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
        </svg>
    </a>
    <br>
    <div class="cards row">
        {% for ad in ads %}
            <div class="col-lg-4 col-md-12 g-4">
                <div class="card">
                    {% if ad.media_files.exists %}
                        {% if ad.media_files.first.return_file_name.lower == 'видео' %}
                            <video class="card-img-top">
                                <source src="{{ ad.media_files.first.file.url }}" type="video/mp4">
                                Ваш браузер не поддерживает тег video.
                            </video>
                        {% elif ad.media_files.first.return_file_name.lower == 'изображение' %}
                            <img class="card-img-top" src="{{ ad.media_files.first.file.url }}" alt="">
                        {% endif %}
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ ad.header }}</h5>
                        <p class="card-text">{{ ad.body|truncatechars:100 }}</p>
                        <a href="{% url 'users:my_ad_detail' ad.id %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Объявлений пока что нет.</p>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/my_responses.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Мои отклики</li>
        </ol>
    </nav>
    <h1>Мои отклики</h1>
    <hr>
    <div class="cards row">
        {% for response in responses %}
            <div class="col-lg-4 col-md-12 g-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Отклик на "{{ response.ad.header }}"</h5>
                        <p class="card-text">{{ response.text }}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Объявлений пока что нет.</p>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/newsletter.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Рассылка</li>
        </ol>
    </nav>
    <h1>Рассылка</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <div class="mb-3">
                <label class="form-label">{{ f.label }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}

users/templates/users/responses_on_my_ads.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Отклики на мои объявления</li>
        </ol>
    </nav>
    {% if selected_ad %}
        <h1>Все отклики на объявление "{{ selected_ad }}"</h1>
    {% else %}
        <h1>Отклики на мои объявления</h1>
    {% endif %}
    <hr>
    <form method="get">
        {% for f in form %}
            <div class="mb-3">
                <label class="form-label">{{ f.label }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Применить</button>
    </form>
    <div class="cards row">
        {% for response in responses %}
            <div class="col-lg-4 col-md-12 g-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Отклик на "{{ response.ad.header }}"</h5>
                        <p class="card-text">{{ response.text }}</p>
                        <div class="d-flex">
                            <a style="margin: 0 20px 0 0;" href="{% url 'users:delete_response' response.ad.id %}"
                               class="btn btn-danger">Удалить</a>
                            <a href="{% url 'users:accept_response' response.ad.id %}"
                               class="btn btn-success">Принять</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Объявлений пока что нет.</p>
        {% endfor %}
    </div>
{% endblock %}