main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:ad_id>/', views.detail_ad, name='detail_ad'),
    path('<int:ad_id>/send_response/', views.send_response, name='send_response'),
    path('create_ad/', views.create_ad, name='create_ad'),
]

service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import os

from users.models import User
from django.db import models


class Ad(models.Model):
    """Модель объявления."""

    class Category(models.TextChoices):
        """Категории."""
        TANKS = 'Танки', 'Танки'
        HEALERS = 'Хилы', 'Хилы'
        DDS = 'ДД', 'ДД'
        MERCHANTS = 'Торговцы', 'Торговцы'
        GUILD_MASTERS = 'Гилдмастеры', 'Гилдмастеры'
        QUEST_GIVERS = 'Квестгиверы', 'Квестгиверы'
        BLACKSMITHS = 'Кузнецы', 'Кузнецы'
        TANNERS = 'Кожевники', 'Кожевники'
        POTION_MAKERS = 'Зельевары', 'Зельевары'
        SPELL_MASTERS = 'Мастера заклинаний', 'Мастера заклинаний'

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ads')
    category = models.CharField(max_length=20, choices=Category.choices, default=Category.TANKS)
    header = models.CharField(max_length=250)
    body = models.TextField()
    people_who_responded = models.ManyToManyField(User, related_name='peoples_who_responded', null=True, blank=True)
    executor = models.ForeignKey(User, on_delete=models.PROTECT, related_name='executor', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.author} - {self.header}'


class MediaFile(models.Model):
    """Модель медиа-файла."""
    ad = models.ForeignKey(Ad, related_name='media_files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='ad_media/')

    def __str__(self):
        return f'{self.return_file_name()} - {self.ad.header}'

    def get_file_extension(self):
        """Возвращает расширение файла."""
        _, file_extension = os.path.splitext(self.file.name)
        return file_extension.lower()

    def return_file_name(self):
        """Возвращает 'Видео' или 'Изображение' в зависимости от расширения."""
        name = ''
        file_extension = self.get_file_extension()
        if file_extension == '.mp4':
            name = 'Видео'
        elif file_extension in ['.jpeg', '.jpg', '.png']:
            name = 'Изображение'
        return name


class Response(models.Model):
    """Модель отклика."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='responses')
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, related_name='responses')
    text = models.TextField()

    def __str__(self):
        return f'{self.user.username} - {self.ad.header}'

main/forms.py
from django import forms

from .models import Ad, Response


class MultipleFileInput(forms.ClearableFileInput):
    """Widget для input с возможностью выбрать более одного файла."""
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class AdForm(forms.ModelForm):
    """Форма объявления."""
    media_files = MultipleFileField(label='Изображения и видео', widget=MultipleFileInput(attrs={
        'multiple': True,
        'class': 'form-control',
    }), required=False)
    header = forms.CharField(label='Заголовок', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    body = forms.CharField(label='Содержание', widget=forms.Textarea(attrs={
        'class': 'form-control',
    }))
    category = forms.ChoiceField(label='Категория', choices=Ad.Category.choices, widget=forms.Select(attrs={
        'class': 'form-control',
    }))

    class Meta:
        model = Ad
        fields = ['header', 'body', 'category']


class SendResponseForm(forms.ModelForm):
    """Форма отклика."""
    text = forms.CharField(label='Текст', widget=forms.Textarea(attrs={
        'class': 'form-control',
    }))

    class Meta:
        model = Response
        fields = ['text']

main/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, redirect

from .forms import AdForm, SendResponseForm
from .models import Ad, MediaFile


@login_required
def index(request):
    """Функция-представление главной страницы."""
    ads = Ad.objects.exclude(author=request.user)
    context = {'ads': ads}
    return render(request, 'main/index.html', context)


@login_required
def create_ad(request):
    """Функция-представление создания объявления."""
    if request.method == 'POST':
        ad_form = AdForm(request.POST)

        if ad_form.is_valid():
            ad = ad_form.save(commit=False)
            ad.author = request.user
            ad.save()
            for file in request.FILES.getlist('media_files'):
                MediaFile.objects.create(ad=ad, file=file)
            return redirect('users:my_ads')

    else:
        ad_form = AdForm()

    return render(request, 'main/ad/create.html', {'ad_form': ad_form})


@login_required
def detail_ad(request, ad_id):
    """Функция-представление детальной информации об объявлении."""
    ad = Ad.objects.get(pk=ad_id)
    is_response_sent = ad.responses.filter(user=request.user)
    context = {'ad': ad, 'is_response_sent': is_response_sent}
    return render(request, 'main/ad/detail.html', context)


@login_required
def send_response(request, ad_id):
    """Функция-представление отправки отклика на объявление."""
    if request.method == 'POST':
        form = SendResponseForm(request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            response.user = request.user
            ad = Ad.objects.get(pk=ad_id)
            response.ad = ad
            if ad.responses.filter(user=response.user):
                raise Http404()
            response.save()
            send_mail(
                subject='На ваше объявление кто-то откликнулся',
                message=f'На ваше объявление "{response.ad.header}" откликнулся пользователь {response.user.username}\n\nДля более детальной информации перейдите в ваши отклики.',
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[response.user.email],
                fail_silently=True,
            )
            return redirect('main:detail_ad', ad_id=ad_id)
    else:
        form = SendResponseForm()
    context = {'form': form}
    return render(request, 'main/ad/send_response.html', context)

main/templates/main/ad/create.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="#">Мои объявления</a></li>
            <li class="breadcrumb-item active" aria-current="page">Создание объявления</li>
        </ol>
    </nav>
    <h1>Создание объявления</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for f in ad_form %}
            <div class="mb-3">
                <label class="form-label">{{ f.label }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
{% endblock %}

main/templates/main/ad/detail.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ ad.header|truncatechars:50 }}</li>
        </ol>
    </nav>
    <h1>{{ ad.header }}</h1>
    <hr>
    <h3>Категория: {{ ad.category }}</h3>
    <br>
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
            {% for media_file in ad.media_files.all %}
                <button type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide-to="{{ forloop.counter0 }}"
                        {% if forloop.counter0 == 0 %}class="active"{% endif %}
                        aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            {% for media_file in ad.media_files.all %}
                <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                    {% if media_file.return_file_name.lower == 'видео' %}
                        <video controls class="d-block w-100">
                            <source src="{{ media_file.file.url }}" type="video/mp4">
                            Ваш браузер не поддерживает тег video.
                        </video>
                    {% elif media_file.return_file_name.lower == 'изображение' %}
                        <img src="{{ media_file.file.url }}" class="d-block w-100" alt="...">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        {% if ad.media_files.count > 1 %}
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        {% endif %}
    </div>
    <br>
    <div style="font-size: 20px;">
        {{ ad.body }}
    </div>
    <br>
    {% if is_response_sent %}
        Вы уже отправили отклик.
    {% else %}
        <a href="{% url 'main:send_response' ad.id %}" type="submit" class="btn btn-primary">Откликнуться</a>
    {% endif %}
    <br>
    <br>
{% endblock %}

main/templates/main/ad/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/ad/list.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

main/templates/main/ad/send_response.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Отправка отклика</li>
        </ol>
    </nav>
    <h1>Отклик</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for f in form %}
            <div class="mb-3">
                <label class="form-label">{{ f.label }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}