main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:ad_id>/', views.detail_ad, name='detail_ad'),
    path('<int:ad_id>/send_response/', views.send_response, name='send_response'),
    path('create_ad/', views.create_ad, name='create_ad'),
]

service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/confirm_code/', views.confirm_code, name='confirm_code'),
    path('my_ads/', views.my_ads, name='my_ads'),
    path('my_ads/<int:ad_id>/', views.my_ad_detail, name='my_ad_detail'),
    path('my_ads/<int:ad_id>/edit_ad/', views.edit_ad, name='edit_ad'),
    path('my_responses/', views.my_responses, name='my_responses'),
    path('responses_on_my_ads/', views.responses_on_my_ads, name='responses_on_my_ads'),
    path('responses_on_my_ads/delete/<int:ad_id>/', views.delete_response, name='delete_response'),
    path('responses_on_my_ads/accept/<int:ad_id>/', views.accept_response, name='accept_response'),
    path('newsletter/', views.newsletter, name='newsletter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Service</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:index' %}">Service</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Главная</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                            {% else %}
                                Анонимный пользователь
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                {% if user.is_staff %}
                                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                                    <li><a class="dropdown-item" href="{% url 'users:newsletter' %}">Рассылка</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'users:my_responses' %}">Мои отклики</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:my_ads' %}">Мои объявления</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:responses_on_my_ads' %}">Отклики на мои
                                    объявления</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'users:logout_user' %}">Выход</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:login_user' %}">Вход</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<main class="content">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>